### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by klefo0** [dfint/dfrus#15] opened 2022-09-18 17:24 UTC
Hello insolor
Vienamese translator here, thank you for much transforming the code base and improve UI, trans engine, that's really amazing. I just test out your code and have this problem 

![image](https://user-images.githubusercontent.com/70630854/190920207-f222c801-7e7a-4838-a146-1367e2586033.png)

Can you look it for bit? I'm using python 3.8

**Comment by insolor** [comment] 2022-09-19 04:54
In general, dfrus is still broken. I fixed some problems in it, but not all of them.

**Comment by insolor** [comment] 2022-09-19 04:55
Duplicate of https://github.com/dfint/dfrus/issues/1

**Closed as completed by insolor** 2022-09-19 04:55 UTC
